### ISSUE TITLE
播放过程中锁屏再解锁报错

### ISSUE THREAD

**Issue by forever1985** [ashqal/MD360Player4Android#114]
在播放过程中，锁屏，然后在解锁，就报错
java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)

**Comment by forever1985** [comment]
java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
                                                               at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
                                                               at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:189)
                                                               at com.asha.vrlib.texture.MD360VideoTexture.texture(MD360VideoTexture.java:99)
                                                               at com.asha.vrlib.plugins.MDPanoramaPlugin.renderer(MDPanoramaPlugin.java:58)
                                                               at com.asha.vrlib.MD360Renderer.onDrawFrame(MD360Renderer.java:110)
                                                               at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
                                                               at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
