### ISSUE TITLE
updateTexImage方法在onresume之后异常

### ISSUE THREAD

**Issue by forever1985** [ashqal/MD360Player4Android#121]
hi，
当暂停播放，再恢复播放视频时，MD360VideoTexture.java中mSurfaceTexture.updateTexImage()会抛出异常

**Comment by HallCheng** [comment]
同上，，，

**Comment by ashqal** [comment]
楼上两位 请问你们是怎么调用暂停的？

**Comment by forever1985** [comment]
在播放视频的时候，可以锁屏，然后解锁，就会报错，必现的

**Comment by ashqal** [comment]
@forever1985 是master上的demo代码？您的系统是？

**Comment by forever1985** [comment]
是的，就是master分支代码，系统是android4.4

**Comment by ashqal** [comment]
我测试了android 7.1.1和android4.3，锁屏 然后解锁，都没有发现你说的问题...

**Comment by forever1985** [comment]
我这边是在播放视频的时候，然后锁屏解锁出现的，刚使用你最新的代码，依然会出现，是播放的网络视频，需要在播放过程中，锁屏，没有声音之后，解锁，就会出现异常了
java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
                                                                                at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
                                                                                at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:189)
                                                                                at com.asha.vrlib.texture.MD360VideoTexture.texture(MD360VideoTexture.java:99)
                                                                                at com.asha.vrlib.plugins.MDPanoramaPlugin.renderer(MDPanoramaPlugin.java:58)
                                                                                at com.asha.vrlib.MD360Renderer.onDrawFrame(MD360Renderer.java:117)
                                                                                at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
                                                                                at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by ashqal** [comment]
[app-debug.apk.zip](https://github.com/ashqal/MD360Player4Android/files/558047/app-debug.apk.zip)
麻烦测试下这个apk包，谢谢

**Comment by forever1985** [comment]
使用你的这个测试包，还是一样的呢

**Comment by hljstardust** [comment]
咋解决呢？

**Comment by ashqal** [comment]
> 咋解决呢？

https://github.com/ashqal/MD360Player4Android/tree/dev-m251
这个分支上还有这个问题吗？
