### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by luigipercuoco** [ashqal/MD360Player4Android#127]
ON MOVERIO BT200:

10-25 11:21:24.335  13097-13097/com.asha.md360player4android E/dalvikvm﹕ Could not find class 'android.widget.ThemedSpinnerAdapter', referenced from method android.support.v7.widget.AppCompatSpinner$DropDownAdapter.<init>
10-25 11:21:41.867  13097-13097/com.asha.md360player4android E/dalvikvm-heap﹕ Out of memory on a 21233680-byte allocation.
10-25 11:21:41.875  13097-13097/com.asha.md360player4android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.OutOfMemoryError
            at android.graphics.Bitmap.nativeCopy(Native Method)
            at android.graphics.Bitmap.copy(Bitmap.java:403)
            at com.asha.vrlib.texture.MD360BitmapTexture$AsyncCallback.texture(MD360BitmapTexture.java:135)
            at com.asha.md360player4android.BitmapPlayerActivity$2.onBitmapLoaded(BitmapPlayerActivity.java:57)
            at com.squareup.picasso.TargetAction.complete(TargetAction.java:36)
            at com.squareup.picasso.Picasso.deliverAction(Picasso.java:558)
            at com.squareup.picasso.Picasso.complete(Picasso.java:510)
            at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:117)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4424)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by ashqal** [comment]
We will keep the soft ref of the bitmap instead of copy it, may fixed in next release(`2.3.0`).
