### ISSUE TITLE
安装运行报错了

### ISSUE THREAD

**Issue by duckzq** [ashqal/MD360Player4Android#155]
System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                              at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                              at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:862)
                                                              at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                              at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                              at java.lang.Thread.run(Thread.java:833)

**Comment by ashqal** [comment]
so引用有问题
