### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.asha.md360player4android.DemoActivity" 

### ISSUE THREAD

**Issue by yinshudi** [ashqal/MD360Player4Android#2]
I can't open the demo app,this is log(Android version 4.4.2):

    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.asha.md360player4android/com.asha.md360player4android.DemoActivity}: java.lang.ClassNotFoundException: Didn't find class "com.asha.md360player4android.DemoActivity" on path: DexPathList[[zip file "/data/app/com.asha.md360player4android-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.asha.md360player4android-1, /vendor/lib, /system/lib]]
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2134)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268)
            at android.app.ActivityThread.access$800(ActivityThread.java:145)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5094)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.asha.md360player4android.DemoActivity" on path: DexPathList[[zip file "/data/app/com.asha.md360player4android-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.asha.md360player4android-1, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
            at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2125)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268)
            at android.app.ActivityThread.access$800(ActivityThread.java:145)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5094)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by ashqal** [comment]
pls try to clean and rebuild it

**Comment by yinshudi** [comment]
I don't run the project,I just download the MD360PlayerDemo.apk and install,but I can't open it.

**Comment by ashqal** [comment]
Reproduced, thank you for your report, I copied the apk file from `/app/build/output` directly and it seems some difference since `Instant Run`, I will fix it.
