### ISSUE TITLE
listview头部添加(GLSurfaceView work with ListView Header)

### ISSUE THREAD

**Issue by jksfood** [ashqal/MD360Player4Android#59]
我想在fragment中的listview的headview中添加你的全景图片，可是我这儿总是报空指针错误，有什么我需要特别注意的地方吗？

**Comment by jksfood** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.opengl.GLSurfaceView.setEGLContextClientVersion(int)' on a null object reference
                                                                   at com.asha.vrlib.MDVRLibrary.initOpenGL(MDVRLibrary.java:129)
                                                                   at com.asha.vrlib.MDVRLibrary.initWithGLSurfaceViewIds(MDVRLibrary.java:121)
                                                                   at com.asha.vrlib.MDVRLibrary.<init>(MDVRLibrary.java:70)
                                                                   at com.asha.vrlib.MDVRLibrary.<init>(MDVRLibrary.java:0)
                                                                   at com.asha.vrlib.MDVRLibrary$Builder.build(MDVRLibrary.java:344)

**Comment by jksfood** [comment]
我将你的MD360PlayerActivity和BitMapPlayerActivity中相应的函数都迁移到了fragment中

**Comment by ashqal** [comment]
这个日志是glSurfaceView没找到，你得先确保glSurfaceView不为null

**Comment by jksfood** [comment]
public class NewSearchFragment extends Fragment {

```
private View parentView;
private View headView;
private ListView listView;
private String [] datas = {"0","2","4","0","2","4","0","2","4","0","2","4","0","2","4","0","2","4","0","2","4","0","2","4","0","2","4","0","2","4"};
private MDVRLibrary mVRLibrary;
private Target mTarget;

public NewSearchFragment() {
    // Required empty public constructor
}

@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
}

@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container,
                         Bundle savedInstanceState) {
    parentView = inflater.inflate(R.layout.fragment_new_search, container, false);

    initView();
    initHeadView();
    initData();

    return parentView;
}

private void initHeadView() {

    mVRLibrary = createVRLibrary();

    // interactive mode switcher
    final Button interactiveModeSwitcher = (Button)headView. findViewById(R.id.button_interactive_mode_switcher);
    interactiveModeSwitcher.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            mVRLibrary.switchInteractiveMode(getActivity());
            updateInteractiveModeText(interactiveModeSwitcher);
        }
    });
    updateInteractiveModeText(interactiveModeSwitcher);

    // display mode switcher
    final Button displayModeSwitcher = (Button)headView. findViewById(R.id.button_display_mode_switcher);
    displayModeSwitcher.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            mVRLibrary.switchDisplayMode(getActivity());
            updateDisplayModeText(displayModeSwitcher);
        }
    });
    updateDisplayModeText(displayModeSwitcher);

    headView.findViewById(R.id.button_reset).setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            mVRLibrary.resetPinch();
            // reset touch
            if (mVRLibrary.getInteractiveMode() == MDVRLibrary.INTERACTIVE_MODE_TOUCH){
                mVRLibrary.resetTouch();
            }
        }
    });

}

private void initData() {
    ArrayAdapter<String> arrayAdapter = new ArrayAdapter<String>(getActivity(),R.layout.for_arraylist,datas);
    listView.setAdapter(arrayAdapter);
}

private void initView() {
    listView = (ListView) parentView.findViewById(R.id.id_listview);
    headView = getActivity().getLayoutInflater().inflate(R.layout.layout_test_headview2,null);
    listView.addHeaderView(headView);

}
```

//    @Override
//    public boolean onTouchEvent(MotionEvent event) {
//        return mVRLibrary.handleTouchEvent(event) || super.onTouchEvent(event);
//    }

```
private void updateDisplayModeText(Button button) {
    String text = null;
    switch (mVRLibrary.getDisplayMode()){
        case MDVRLibrary.DISPLAY_MODE_NORMAL:
            text = "NORMAL";
            break;
        case MDVRLibrary.DISPLAY_MODE_GLASS:
            text = "GLASS";
            break;
    }
    if (!TextUtils.isEmpty(text)) button.setText(text);
}

private void updateInteractiveModeText(Button button){
    String text = null;
    switch (mVRLibrary.getInteractiveMode()){
        case MDVRLibrary.INTERACTIVE_MODE_MOTION:
            text = "MOTION";
            break;
        case MDVRLibrary.INTERACTIVE_MODE_TOUCH:
            text = "TOUCH";
            break;
    }
    if (!TextUtils.isEmpty(text)) button.setText(text);
}
```

//    @Override
//    protected void onResume() {
//        super.onResume();
//        mVRLibrary.onResume(this);
//    }
//
//    @Override
//    protected void onPause() {
//        super.onPause();
//        mVRLibrary.onPause(this);
//    }
//
//    @Override
//    protected void onDestroy() {
//        super.onDestroy();
//        mVRLibrary.onDestroy();
//    }

```
@Override
public void onResume() {
    super.onResume();
    mVRLibrary.onResume(getActivity());
}

@Override
public void onPause() {
    super.onPause();
    mVRLibrary.onPause(getActivity());
}

@Override
public void onDestroy() {
    super.onDestroy();
    mVRLibrary.onDestroy();
}

@Override
public void onDetach() {
    super.onDetach();
}

private MDVRLibrary createVRLibrary() {
    return MDVRLibrary.with(getActivity())
            .displayMode(MDVRLibrary.DISPLAY_MODE_NORMAL)
            .interactiveMode(MDVRLibrary.INTERACTIVE_MODE_MOTION)
            .bitmap(new MDVRLibrary.IBitmapProvider() {
                @Override
                public void onProvideBitmap(final MD360BitmapTexture.Callback callback) {
                    Uri uri = getDrawableUri(R.drawable.texture);
                    loadImage(uri,callback);
                }
            })
            .gesture(new MDVRLibrary.IGestureListener() {
                @Override
                public void onClick(MotionEvent e) {
                    Toast.makeText(getActivity(), "onClick!", Toast.LENGTH_SHORT).show();
                }
            })
            .pinchEnabled(true)
            .build(R.id.surface_view1,R.id.surface_view2);
}

private void loadImage(Uri uri, final MD360BitmapTexture.Callback callback){
    mTarget = new Target() {
        @Override
        public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
            callback.texture(bitmap);
            cancelBusy();
        }

        @Override
        public void onBitmapFailed(Drawable errorDrawable) {

        }

        @Override
        public void onPrepareLoad(Drawable placeHolderDrawable) {

        }
    };
    Picasso.with(getActivity()).load(uri).into(mTarget);
}

public void cancelBusy(){
    parentView.findViewById(R.id.progress).setVisibility(View.GONE);
}

private Uri getDrawableUri(@DrawableRes int resId){
    Resources resources = getResources();
    return Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE + "://" + resources.getResourcePackageName(resId) + '/' + resources.getResourceTypeName(resId) + '/' + resources.getResourceEntryName(resId) );
}
```

}

**Comment by jksfood** [comment]
这个是我集成的方式，我实在看不出来哪里有问题会使得空指针异常，headview的布局文件直接使用的你的布局文件，控件id什么的我都没改

**Comment by ashqal** [comment]
onCreateView还没有把parentView return掉，
就开始build(R.id.surface_view1,R.id.surface_view2)

而这个build是activity.findViewById(glSurfaceViewId)来实现view的查找的，
所以肯定找不到这个GLSurfaceView

我加个方法做个兼容吧

**Comment by jksfood** [comment]
哦哦，我把initHeadView()和initData()放在了onResume中不崩溃了，但是createVRLibrary（）中的方法好像没有执行

**Comment by ashqal** [comment]
``` java
compile 'com.github.ashqal:MD360Player4Android:529fdb628d'
```

增加了一个方法

``` java
public MDVRLibrary build(GLSurfaceView glSurfaceView)
```

把GLSurfaceView找出来，传进去就可以了

另外1.4.0版本开始，只需要一个GLSurfaceView就可以了

**Comment by jksfood** [comment]
哦哦，我试试

**Comment by jksfood** [comment]
确实，在onCreateView中build（R.id.surface_view）也不报错了，但是，createVRLibrary重中的return语句并没有执行，这是为什么？是调用的方式不对吗？我是在fragment中调用的

**Comment by jksfood** [comment]
界面上只有3个button，并没有图片显示出来

**Comment by ashqal** [comment]
1.别放在onResume
2.用build((GLSurfaceView)parentView.findViewById(R.id.surface_view))

**Comment by jksfood** [comment]
不行，
private MDVRLibrary createVRLibrary() {

```
    MyLog.e(StaticConstantClass.TAG,"loadImage  createVRLibrary");

    return MDVRLibrary.with(getActivity())

            .displayMode(MDVRLibrary.DISPLAY_MODE_NORMAL)
            .interactiveMode(MDVRLibrary.INTERACTIVE_MODE_MOTION)
            .bitmap(new MDVRLibrary.IBitmapProvider() {
                @Override
                public void onProvideBitmap(final MD360BitmapTexture.Callback callback) {
                    MyLog.e(StaticConstantClass.TAG," loadImage  onProvideBitmap");
                    Uri uri = getDrawableUri(R.drawable.texture);
                    loadImage(uri,callback);
                }
            })
            .gesture(new MDVRLibrary.IGestureListener() {
                @Override
                public void onClick(MotionEvent e) {
                    Toast.makeText(getActivity(), "onClick!", Toast.LENGTH_SHORT).show();
                }
            })
            .pinchEnabled(true)
            .build((GLSurfaceView)headView.findViewById(R.id.surface_view));
}
```

return 中的语句没有被执行，只打印了MyLog.e(StaticConstantClass.TAG,"loadImage  createVRLibrary");

**Comment by ashqal** [comment]
return肯定执行了 下面这种链式调用就只算一句的

**Comment by jksfood** [comment]
那为啥  onProvideBitmap 这个函数中的MyLog.e(StaticConstantClass.TAG," loadImage  onProvideBitmap");没有被打印。

**Comment by ashqal** [comment]
要不发我个小demo到邮箱 我帮你看看？

**Comment by jksfood** [comment]
嗯  那太好了，我整理下，稍后发给你

**Comment by jksfood** [comment]
邮件已发！ashqalcn@gmail.com

**Comment by ashqal** [comment]
收到了 是个很奇怪的问题 renderer不回调

**Comment by jksfood** [comment]
嗯，是不是跟fragment有关系，调用环境不一样了

**Comment by ashqal** [comment]
1.根layout，设置一个固定高度

``` java
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="300dp"
    >

    <FrameLayout
        android:orientation="horizontal"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <android.opengl.GLSurfaceView
            android:id="@+id/surface_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
        <!--<android.opengl.GLSurfaceView-->
            <!--android:id="@+id/surface_view2"-->
            <!--android:layout_weight="1"-->
            <!--android:layout_width="0dp"-->
            <!--android:layout_height="match_parent" />-->
    </FrameLayout>
....
</RelativeLayout>
```

2.header创建

``` java
headView = getActivity().getLayoutInflater().inflate(R.layout.layout_test_headview2,listView,false);
```

**Comment by jksfood** [comment]
真的可以了，感谢！
