### ISSUE TITLE
Crash in mTexture#updateTexture after resume on some device.

### ISSUE THREAD

**Issue by ashqal** [ashqal/MD360Player4Android#69]
``` java
   java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
       at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
       at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:163)
       at com.asha.vrlib.texture.MD360VideoTexture.updateTexture(MD360VideoTexture.java:90)
       at com.asha.vrlib.MD360Renderer.onDrawFrame(MD360Renderer.java:83)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

```

**Comment by xunmengyoufeng** [comment]
Hi,have you resolve the problem? If you resolved, can you tell me how can i resolve it, Thanks.
