### ISSUE TITLE
【BUG】播放时偶发崩溃 异常为：java.lang.RuntimeException: Error during updateTexImage

### ISSUE THREAD

**Issue by scar1et** [ashqal/MD360Player4Android#82]
java.lang.RuntimeException: Error during updateTexImage
    at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
    at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:240)
    at com.asha.vrlib.texture.MD360VideoTexture.updateTexture(MD360VideoTexture.java:93)
    at com.asha.vrlib.MD360Renderer.onDrawFrame(MD360Renderer.java:83)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

**Comment by ashqal** [comment]
你用的是1.5.3吗？1.5.3已经修复了这个bug了

**Comment by scar1et** [comment]
就是1.5.3啊，还是有这个bug

**Comment by ashqal** [comment]
demo里有复现吗？机型是什么？复现步骤是？

**Comment by scar1et** [comment]
demo没重现，偶发，重现不了。
机型是与系统
三星GT-I9500，Android 4.4
三星n9109w，Android 5.1
这俩设备都出现过

**Comment by ashqal** [comment]
你是不是从以前的版本升级到1.5.3，但是使用了以前的MediaPlayerWrapper?

**Comment by scar1et** [comment]
不是，我刚刚开始使用的时候就是用的1.5.3

**Comment by ashqal** [comment]
是有特殊的使用方式吗？

**Comment by scar1et** [comment]
有切换视频逻辑，切换视频方法见 #83 
其余没啥特殊的了，都是按你demo改的

**Comment by ashqal** [comment]
还有复现吗？

**Comment by ashqal** [comment]
先关了 还有问题请再reopen吧

**Comment by scar1et** [comment]
好的
